#Create issuer for a selfsigned certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-selfsigned-issuer
  #namespace: cert-manager
spec:
  selfSigned: {}

---
#Create selfsigned certificate to be CA certificate and store it in ca-secret
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: kubernetes
  subject:
    organizations:
      - Home
    organizationalUnits:
      - Kubernetes
  secretName: ca-secret
  privateKey:
    algorithm: ECDSA
    size: 521
  issuerRef:
    name: ca-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io 

---
#Create issuer for CA, which uses cert and key stored in ca-secret to sign certificates.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  #namespace: cert-manager
spec:
  ca:
    secretName: ca-secret
