#!/bin/bash

echo 1. Verifying kubernetes installation
if [ -f /etc/sysctl.d/kubernetes.conf ]; then
  echo 2. Check node status
  node=(`kubectl get nodes | tr -s ' ' | awk '{print $1}' | tail -n +2`)
  status=(`kubectl get nodes | tr -s ' ' | awk '{print $2}' | tail -n +2`)
  error=0
  for ((i=0; i<${#node[@]}; i++)); do
    if [ "$status[$i]" != "Ready" ]; then
      echo " Node $node[$i] is not Ready.  Actual status: $status[$i]"
      ((error ++))
    fi
  done
  if [ "$error" == "0" ]; then
    echo " All nodes are ready"
  fi

else
  echo "This script should be run on kubernetes master node"
fi
