#!/bin/bash
# Copyright 2025 The ollama-k8s Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo 1. Verifying kubernetes installation
if [ -f /etc/sysctl.d/kubernetes.conf ]; then
  echo 2. Check node status
  node=(`kubectl get nodes | tr -s ' ' | awk '{print $1}' | tail -n +2`)
  status=(`kubectl get nodes | tr -s ' ' | awk '{print $2}' | tail -n +2`)
  error=0
  for ((i=0; i<${#node[@]}; i++)); do
    if [ "$status[$i]" != "Ready" ]; then
      echo " Node $node[$i] is not Ready.  Actual status: $status[$i]"
      ((error ++))
    fi
  done
  if [ "$error" == "0" ]; then
    echo " All nodes are ready"
  fi

else
  echo "This script should be run on kubernetes master node"
fi
