#!/bin/bash
# Copyright 2025 The ollama-k8s Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo 1. Allow port 7946
if [ "`sudo ufw status`" == *" active" ]; then
  sudo ufw allow 7946/tcp && sudo ufw allow 7946/udp
fi

echo 2. Set strict ARP
kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl diff -f - -n kube-system
if [ "$?" != "0" ]; then
  kubectl get configmap kube-proxy -n kube-system -o yaml | sed -e "s/strictARP: false/strictARP: true/" | kubectl apply -f - -n kube-system
fi

echo 3. Add Metallb with KRR-k8s to master node
master=`kubectl get nodes | grep control-plane | awk '{print $1}'`
sed -i "s/NODENAME/nodeName: $master/g' metallb-frr-k8s-v0.15.2.yaml
kubectl apply -f metallb-frr-k8s-v0.15.2.yaml

echo 4. Apply configmap
kubectl apply -f metallb-configmap.yaml


