apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
  - name: metallb-l2
    protocol: layer2
    addresses:
    - 192.168.1.240-192.168.1.250
