# Copyright 2025 The ollama-k8s Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webui-cert
  namespace: ollama
spec:
  isCA: false
  commonName: webui.kubernetes
  subject:
    organizations:
      - kubernetes
    organizationalUnits:
      - ollama
  secretName: webui-secret
  privateKey:
    algorithm: ECDSA
    size: 384
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "90"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-redirect-from: http://
    nginx.ingress.kubernetes.io/proxy-redirect-to: https://
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "300"
  name: webui-ingress
  namespace: ollama
spec:
  ingressClassName: nginx
  rules:
  - host: webui.kubernetes
    http:
      paths:
      - backend:
          service:
            name: webui-svc
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - webui.kubernetes
    secretName: webui-secret
