# Copyright 2025 The ollama-k8s Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Namespace
metadata:
  name: ollama
  labels:
    environment: production
    team: onemanband
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deploy
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      nodeName: NODENAME
      containers:
      - name: ollama
        image: ollama/ollama:latest
        volumeMounts:
          - mountPath: /root/.ollama
            name: ollama-storage
        ports:
        - name: container-port
          containerPort: 11434
          protocol: TCP
        env:
        - name: PRELOAD_MODELS
          value: "llama3.2-vision:latest"
        - name: OLLAMA_KEEP_ALIVE
          value: "12h"
        - name: OLLAMA_DEBUG
          value: "2"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "for model in $PRELOAD_MODELS; do ollama run $model \"\"; done"]
      volumes:
      - hostPath:
          path: /opt/ollama
          type: DirectoryOrCreate
        name: ollama-storage
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    name: ollama
  ports:
  - port: 80
    name: http
    targetPort: container-port
    protocol: TCP
