# Copyright 2025 The ollama-k8s Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deploy
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webui
  template:
    metadata:
      labels:
        name: webui
    spec:
      volumes:
      - hostPath:
          path: /opt/webui
          type: DirectoryOrCreate
        name: webui-storage
      nodeName: NODENAME
      containers:
        - name: webui
          image: ghcr.io/open-webui/open-webui:latest
          volumeMounts:
          - mountPath: /app/backend/data
            name: webui-storage
          env:
            - name: OLLAMA_BASE_URLS
              value: "http://ollama-svc"
          ports:
            - name: container-port
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webui-svc
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    name: webui
  ports:
  - port: 80
    name: http
    targetPort: container-port
    protocol: TCP
  - port: 443
    name: https
    targetPort: container-port
    protocol: TCP
